Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  
  config.vm.define "msisdnserver" do |msisdnserver|
  end
  
  config.vm.network "forwarded_port", guest: 80, host: 5555
  
  config.vm.synced_folder "..", "/var/www/MsisdnJsonRpcApi"

  config.vm.provision :puppet do |puppetbase|
    puppetbase.manifests_path = 'puppet/manifests'
    puppetbase.manifest_file = 'puppetbase.pp'
  end
  
  config.vm.provision :puppet do |initserver|
    initserver.manifests_path = 'puppet/manifests'
    initserver.manifest_file = 'initserver.pp'
  end
end


