Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.network "forwarded_port", guest: 80, host: 5000
  
  config.vm.synced_folder "..", "/var/www/MsisdnJsonRpcApi"
  
  config.vm.provision :shell do |shell|
  shell.inline = "mkdir -p /vagrant/puppet/modules
                 (puppet module list | grep puppetlabs-apache) ||
                 puppet module install puppetlabs/apache
                 (puppet module list | grep willdurand/composer) ||
                 puppet module install willdurand/composer"
  end  
  
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path = 'puppet/modules'
    puppet.manifest_file = 'init.pp'
  end
end


